name: Test Kind CI

on:
  push:
    branches: [ main ]  # or the branch you want to test

jobs:
  test-kind:
    runs-on: [self-hosted, kind]  # will run on your local runner

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build test Docker image
        run: |
          docker build -t howco/devops-dir:test-foobarbaz ./api-golang

      - name: Push test Docker image
        run: |
          docker push howco/devops-dir:test-foobarbaz

      - name: Set kubectl context to Kind
        run: |
          kubectl config use-context kind-kind

      - name: Deploy test pod
        run: |
          kubectl create deployment test-nginx --image=howco/devops-dir:test-foobarbaz || true
          kubectl rollout status deployment/test-nginx --timeout=60s

      - name: Cleanup
        run: |
          kubectl delete deployment test-nginx || true
